### ISSUE TITLE
Finished Material

### ISSUE THREAD

**Issue by mcborseth** [R-L-Packaging/R-L-Inventory#2]
size showing on screen repeats width and does not show depth
Love to see description and item number on main screen - more important than color and Flute
Edit button would be nice - 
I am also thinking QR code might be helpful on these items as we repeat and move them around

also is it possible to at a column for sheets or in production - ie we have sheet and are making them so we don't need to order them yet

Is there a company column on this on as this is where it is most improtant

on that front - could we have the tabs up top be:
All
AWPL
CK
FVD
Other

**Comment by JedBorseth** [comment]
> also is it possible to at a column for sheets or in production - ie we have sheet and are making them so we don't need to order them yet

Not sure what you mean by this, everything else should be implemented as of my latest changes

**Comment by mcborseth** [comment]
So ya
Add a column in finished product for sheets that are in production.  So we
have 200 boxes in stock and have 100 custom sheets that are in production
to make 100 more boxes.  So then I know not to order 100 more sheets cause
we already got them.  Does that makes sense

**Comment by JedBorseth** [comment]
Second amount column called in production will be very similar to amount with modal on click and everything


This will add to amount before emailing
